### PR TITLE
Fix errors in writer loops and omit cancelation after trailers written

### LINKED ISSUE #148: http2 INTERNAL_ERROR when combining vanguard with httputil.ReverseProxy
For reasons outside my control, I have a server that only serves grpc-web code and a client that only supprts grpc. I was looking to combine vanguard with reverse proxy to bridge the two. 

However, when trying to combine a vanguard transcoder with `httputil.NewSingleHostReverseProxy`, I'm running into some unexpected stream resets being presented to the client as `INTERNAL_ERROR`. Repro steps:

```go
package bug

import (
	"context"
	"crypto/tls"
	"fmt"
	"net"
	"net/http"
	"net/http/httptest"
	"net/http/httputil"
	"net/url"
	"testing"

	"buf.build/gen/go/connectrpc/eliza/connectrpc/go/connectrpc/eliza/v1/elizav1connect"
	elizav1 "buf.build/gen/go/connectrpc/eliza/protocolbuffers/go/connectrpc/eliza/v1"
	"connectrpc.com/connect"
	"connectrpc.com/vanguard"
	"github.com/stretchr/testify/require"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/reflect/protoregistry"
)

func TestINTERNAL_ERROR(t *testing.T) {

	// GRPC-web server (normally process 1)
	mux := http.NewServeMux()
	mux.Handle(elizav1connect.NewElizaServiceHandler(&handler{t: t}))
	grpcwebServer := httptest.NewUnstartedServer(
		h2c.NewHandler(mux, &http2.Server{}),
	)
	grpcwebServer.EnableHTTP2 = true
	grpcwebServer.Start()
	defer grpcwebServer.Close()

	// Vanguard based proxy (normally process 2)
	url, err := url.Parse(grpcwebServer.URL)
	require.NoError(t, err)
	proxy := httputil.NewSingleHostReverseProxy(url)
	proxy.FlushInterval = -1 // shouldn't be necessary
	// Normally I load these from a file, but since everything is in the same process for the test grab them here
	schema, err := protoregistry.GlobalFiles.FindDescriptorByName("connectrpc.eliza.v1.ElizaService")
	require.NoError(t, err)
	transcoder, err := vanguard.NewTranscoder(
		[]*vanguard.Service{vanguard.NewServiceWithSchema(schema.(protoreflect.ServiceDescriptor), proxy)},
		vanguard.WithDefaultServiceOptions(
			vanguard.WithTargetProtocols(vanguard.ProtocolGRPCWeb),
			vanguard.WithTargetCodecs(vanguard.CodecProto),
		),
		vanguard.WithUnknownHandler(proxy),
	)
	require.NoError(t, err)
	vanguardServer := httptest.NewUnstartedServer(
		h2c.NewHandler(
			http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				// https://cs.opensource.google/go/go/+/master:src/net/http/httputil/reverseproxy.go;l=520;drc=960654be0c4ad7918376e2e1d47491c9bc7520e0
				// https://github.com/connectrpc/vanguard-go/blob/c6d89f4b3bbda0b6fa4737a9bb2c4425c4a23bfa/transcoder.go#L1530
				// https://github.com/connectrpc/vanguard-go/blob/c6d89f4b3bbda0b6fa4737a9bb2c4425c4a23bfa/transcoder.go#L1329-L1362
				//
				// defer func() {
				// 	if r := recover(); r != nil {
				// 		if r != http.ErrAbortHandler {
				// 			panic(r)
				// 		}
				// 	}
				// }()
				t.Log("vanguard server: ", r.Header)
				transcoder.ServeHTTP(w, r)
			}),
			&http2.Server{},
		),
	)
	vanguardServer.EnableHTTP2 = true
	vanguardServer.Start()
	defer vanguardServer.Close()

	// grpc client using h2c (normally process 3)
	h2cClient := &http.Client{
		Transport: &http2.Transport{
			AllowHTTP: true,
			DialTLS: func(network, addr string, cfg *tls.Config) (net.Conn, error) {
				return net.Dial(network, addr)
			},
		},
	}
	client := elizav1connect.NewElizaServiceClient(h2cClient, vanguardServer.URL, connect.WithGRPC(), connect.WithProtoJSON())
	unaryResp, err := client.Say(context.Background(), connect.NewRequest(&elizav1.SayRequest{Sentence: "foo"}))
	require.NoError(t, err)
	require.Equal(t, unaryResp.Msg.Sentence, "echo foo")

	serverStream, err := client.Introduce(context.Background(), connect.NewRequest(&elizav1.IntroduceRequest{Name: "foo"}))
	require.NoError(t, err)
	var responses []string
	for serverStream.Receive() {
		responses = append(responses, serverStream.Msg().Sentence)
	}
	require.NoError(t, serverStream.Err())
	require.Equal(t, []string{"hi", "hi again"}, responses)
}

type handler struct {
	elizav1connect.UnimplementedElizaServiceHandler
	t testing.TB
}

func (h *handler) Say(ctx context.Context, req *connect.Request[elizav1.SayRequest]) (*connect.Response[elizav1.SayResponse], error) {
	if req.Peer().Protocol != connect.ProtocolGRPCWeb {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("only accepts grpc-web, got %q", req.Peer().Protocol))
	}
	h.t.Log("connect handler: ", req.Header())
	return connect.NewResponse(&elizav1.SayResponse{Sentence: "echo " + req.Msg.Sentence}), nil
}

func (h *handler) Introduce(ctx context.Context, req *connect.Request[elizav1.IntroduceRequest], resp *connect.ServerStream[elizav1.IntroduceResponse]) error {
	if req.Peer().Protocol != connect.ProtocolGRPCWeb {
		return connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("only accepts grpc-web, got %q", req.Peer().Protocol))
	}
	resp.Send(&elizav1.IntroduceResponse{Sentence: "hi"})
	resp.Send(&elizav1.IntroduceResponse{Sentence: "hi again"})
	return nil
}
```

```
$ GODEBUG=http2debug=1 go test . -v
2024/11/03 14:48:21 http2: Transport received RST_STREAM stream=3 len=4 ErrCode=INTERNAL_ERROR
    vanguard_test.go:88: 
                Error Trace:    /Users/robbert/Desktop/vanguard_test.go:88
                Error:          Received unexpected error:
                                internal: stream error: stream ID 3; INTERNAL_ERROR; received from peer
                Test:           TestINTERNAL_ERROR
--- FAIL: TestINTERNAL_ERROR (0.00s)
FAIL
FAIL    bug     0.011s
FAIL
```

From my peek into this 
https://cs.opensource.google/go/go/+/master:src/net/http/httputil/reverseproxy.go;l=520;drc=960654be0c4ad7918376e2e1d47491c9bc7520e0 panics on the error setup in:
https://github.com/connectrpc/vanguard-go/blob/c6d89f4b3bbda0b6fa4737a9bb2c4425c4a23bfa/transcoder.go#L1530 which seems to be propagated in the `w.currentIsTrailer` branch when `err==nil` after it doesn't break but until it reaches the top of the loop again on the `w.err != nil` condition in `envelopingWriter`:  https://github.com/connectrpc/vanguard-go/blob/c6d89f4b3bbda0b6fa4737a9bb2c4425c4a23bfa/transcoder.go#L1328-L1362

Not sure if this is a right root cause or if it's something due to how `httputil.NewSingleHostReverseProxy` does buffering. As workaround I'm now catching the panic in the vanguard handler which seems to work ok for the client/server but is probably not good long term :)

### PR DESCRIPTION
**Pull request by jhump**
There was a logic bug in `envelopingWriter` and `transformingWriter` that could cause it to spuriously return a non-nil error after it had finished writing trailers for a response.

There was also an issue with `responseWriter.reportEnd`, which would cancel the operation context, which could then cause the handler to freak out. In particular, `httputil.ReverseProxy` could observe a context cancelation when trying to proxy the response bytes (even though all response bytes were copied and the cancellation was right after the final byte was written). The reverse proxy, when it encounters an error, will `panic(http.ErrAbortWrite)`, which then causes the HTTP/2 stream to be cancelled (if HTTP/2 is used) instead of a normal stream termination.

This adds the entirety of the repro test case in #148, almost verbatim, to tests in this repo.

Resolves #148.

### CODE REVIEW

File: transcoder.go [hunk 1]
```diff
@@ -1607,6 +1615,10 @@ func (w *transformingWriter) Write(data []byte) (n int, err error) {
 				w.rw.reportError(err)
 				return written, err
 			}
+			if w.trailerWritten && len(data) == 0 {
```
Comment (emcfarlane) [inline transcoder.go:1618]: Can the state flag `w.trailerWritten` be removed here and changed to:
```go
if w.latestEnvelope.trailer && len(data) == 0 { ... }
```

**Review by emcfarlane — APPROVED** [review]

File: transcoder.go (hunk 1 above)
Comment (jhump) [reply transcoder.go]: Yeah, I think you're right. Done.

**Review by emcfarlane — APPROVED** [review]
